### ISSUE TITLE
Removing incremental snapshots

### ISSUE THREAD

**Issue by blalor** [elasticsearch/curator#219]
Is it possible to configure curator so that it keeps, say, 1 day of hourly snapshots, 1 week of daily snapshots, 1 month of weekly snapshots, etc?  There's really no overhead in keeping many snapshots, but from an operational perspective it'd be nice to keep these thinned out.

**Comment by untergeek** [comment]
There is much new functionality for filtering snapshots (and indices) in v3.  This will still not be possible in a single command, however.
