### ISSUE TITLE
Curator API does not support explicit operation timeouts; no way to handle network issues early on

### ISSUE THREAD

**Issue by dbeckham** [elasticsearch/curator#228]
It appears that the curator API uses a global timeout for any operation, including basic connection handling. For the most part, every elasticsearch-py API method has an operational level timeout argument, either named ```timeout``` or ```master_timeout``` in the case of SnapshotClient.

If you are creating a snapshot, or any long running operation, and need to set a large timeout like 21600, as the curator_script.py does, any network issue, downed host or configuration problem would take 6 hours before it failed.

Please consider adding individual timeout support to the curator API methods.

**Comment by untergeek** [comment]
The `--request-timeout` flag is now available for the optimize and snapshot commands with v3.
