### ISSUE TITLE
re-open an index?

### ISSUE THREAD

**Issue by Grauen** [elasticsearch/curator#239]
Hi guys, it is pretty easy with curator to close indices - but how can I re-open them? 

Our scenario: 

We collect data about our system activities over many months. After 3 months of collecting data, our Kibana dashboards become a little slow. So we use curator to close the indices which are older than 30 days. Two months later we want to restore this data because we want to compare our current data with historized data of our closed indices. At this point it is not possible to re-open indices using curator, isn't it? 

It would be great if you could bring this feature with your next release. At this point we can use curator to close indices but we have to manually call elasticsearch to reopen data. 

Cheers,

Grauen

**Comment by untergeek** [comment]
Opening indices is now in v3.0.0
