### ISSUE TITLE
Skip replica count change if not needed

### ISSUE THREAD

**Issue by bobrik** [elasticsearch/curator#246]
I have 400+ daily indices and curator tries to set new replica count for every index that matched desired time span. This takes a while and could be avoided by simple check for current replica count.

```
2015-01-11 09:34:40,932 INFO      change_replicas operation succeeded on statistics-20131004
...
2015-01-11 09:39:50,985 INFO      change_replicas operation succeeded on statistics-20141004
```

5+ minutes to do nothing.

I can send a PR if you're interested.

**Comment by untergeek** [comment]
@bobrik This will be easily addressed with the pipelining feature pending in 3.0.

**Comment by untergeek** [comment]
However, if you want to do a short-term PR for count validation, I will accept it and merge it to master.

**Comment by untergeek** [comment]
While checking replica count could help, most of the need for this is obviated with better index filtering, in v3.  Also, all matching indices get the replica count updated simultaneously in v3.

I have removed these checks for now.  If they are desired, we can re-add them to v3.
