### ISSUE TITLE
Logstash log format should always produce proper JSON

### ISSUE THREAD

**Issue by magnusbaeck** [elasticsearch/curator#248]
With `--logformat logstash`, Curator uses the standard log formatter ([logging.Formatter](https://docs.python.org/2/library/logging.html#logging.Formatter)) and just configures the format string to produces something that's _usually_ valid JSON. However, if the message or another field from the log record contains e.g. a backslash or a double quote this results in broken JSON. We should instead use a formatter that always produces proper JSON (e.g. using [Python's json module](https://docs.python.org/2/library/json.html)).

I'm almost done with a patch for this. Does the Elasticsearch CLA cover Curator as well?

**Comment by untergeek** [comment]
That is why the code was updated with `json.dumps` in the places where that could happen.

https://github.com/elasticsearch/curator/search?utf8=✓&q=json.dumps

It's one of the changes in [Curator 2.1.0](https://github.com/elasticsearch/curator/blob/059b99e3bafc3d86288af059be748455be03533c/Changelog.rst#210-30-december-2014)

If there are other places this can happen that I have missed, I would prefer to keep the usage similar.

**Comment by magnusbaeck** [comment]
Don't know how I managed to miss that bug. I thought I searched for "logstash".

Wait, what? You prefer having to manually insert json.dumps() calls for log messages that you think can contain characters that screw up the output?

Maybe I'm too tired, but I don't see how it's supposed to work – json.dumps() obviously returns a double quoted, but the formatter's format string also includes literal double quotes for the message, resulting in double double quotes in the final rendered message. Here's an example message from a stock Curator 2.1.1 with `--loglevel DEBUG` and `--logformat logstash`, and it's not valid JSON:

    {"@timestamp":"2015-01-13T23:35:10.623Z", "loglevel":"DEBUG", "name":"curator", "function":"filter_by_timestamp", "linenum":"375", "message":""Unable to match logstash-2014.07.31_ with regular expression ^logstash-(\\d{4}\\.\\d{2}\\.\\d{2})$.  Error: 'NoneType' object has no attribute 'group'""}

**Comment by untergeek** [comment]
Looks like `json.dumps` didn't wrap that properly.  I wonder why not. Looks like a better solution is in order.

So, what does your PR look like?

**Comment by magnusbaeck** [comment]
Before I can publish a PR I need to know whether Curator is covered by the Elasticsearch CLA or if I need to get approval from my employer. I can't find anything indicating that Curator _is_ covered but it would be surprising if it wasn't when Logstash and Elasticsearch itself are covered.

But, basically it's a ~15-line class descending from logging.Formatter that overrides format(), plus the obvious adjustments of the logging configuration in main(). Alternatively, we could choose to use [github.com/exoscale/python-logstash-formatter](https://github.com/exoscale/python-logstash-formatter) if we think it's worth introducing a library dependency to avoid those 15 lines.

**Comment by untergeek** [comment]
Yes, the CLA covers Curator as well.

**Comment by untergeek** [comment]
Closed by #250
