### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by hydrapolic** [elasticsearch/curator#251]
I failed to find this information, but does curator work in Python3?

A quick test with 2.1.1:
$ curator 

2015-01-15 05:43:29,902 INFO      Job starting...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.3/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
  File "/usr/lib64/python3.3/site-packages/curator/curator_script.py", line 354, in main
    if arguments.timestring:
AttributeError: 'Namespace' object has no attribute 'timestring'

**Comment by untergeek** [comment]
When all was unified, it did work with python 3.  Since the split of the API to `curator.py` and the script functions to `curator_script.py`, some of the args in `curator_script.py` do not like Python 3.  It will require a refactor.

**Comment by untergeek** [comment]
The API passes all tests with python 3, by the way.

**Comment by grahamc** [comment]
From IRC today:

```
 gchristensen | Hi, does elasticsearch-curator work with python2? or python3? or both?
    untergeek | currently it should only be used with python2
 gchristensen | ok, thank you untergeek
    untergeek | because of some weirdness with the script changes and python3
```

**Comment by untergeek** [comment]
I have tested curator v3.0.0-beta2 with Python 3.4.2 and all tests are passing.
