### ISSUE TITLE
Request for v3 - enable use of curator for a specified non-time-based index 

### ISSUE THREAD

**Issue by rtkmhart** [elasticsearch/curator#263]
We have many non-time based indices that we would like to manage with curator, for snapshots, open/close, etc. There's no way (unless I'm totally missing it) to specify a non-time-based index name or pattern. Please consider adding this functionality.

Not having this capability means we need to somewhat duplicate curator's functionality for these indices. 

I will happily help add this functionality if need be.

**Comment by untergeek** [comment]
This now works in curator v3.  See: https://github.com/elasticsearch/curator/blob/master/docs/asciidoc/index.asciidoc#index
