### ISSUE TITLE
Update no_more_bloom version

### ISSUE THREAD

**Issue by cfeio** [elasticsearch/curator#267]
In Curator.py the bloom operation is configured to only run if ES version is below 1.5 and says 'Bloom filters no longer exist in Elasticsearch since v1.5.0'. 

This documentation indicates that bloom filters were removed in 1.4: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-update-settings.html

Here is the specific pull request that disabled these by default: https://github.com/elasticsearch/elasticsearch/pull/6959

**Comment by untergeek** [comment]
Yeah.  I made the change for a 1.x dev branch thinking they weren't going to release it until 1.5.  I never changed it after it was merged into 1.4.
