### ISSUE TITLE
Optionally allow some changes to closed indices

### ISSUE THREAD

**Issue by ferki** [elasticsearch/curator#279]
I think there are some cases when it would actually be useful to be able to apply some of the changes curator supports even to closed indices.

For example when someone uses an age-based data retention plan, like having indexer and storage nodes, and keeping old indices around in a closed state for a while before they actually get deleted/backed up. I believe that is quite a common setup when dealing with logs or other time-based data, especially on a high volume.

In the above scenario it can be the case that the allocation rules are changing between the closing and the reopening of old indices, so they might start recovering to the wrong nodes (which can be painful if huge amounts of data is involved).

This can be prevented if there would be an `--even-for-closed-indices` switch for e.g. the `allocation` command, but it would possibly be useful for some other operations as well _as an option_ (`replicas`? maybe `alias`? ). So interim allocation rule changes are constantly could be applied even to closed indices if that makes sense for someone's use case.

I have a simple implementation of this at hand against v2, and I'm willing to convert it to v3 if it sounds like a good idea.

**Comment by ferki** [comment]
Ok, `alias` is ruled out by #214.

**Comment by untergeek** [comment]
I'm checking right now, but I'm fairly certain that you cannot take any action against a closed index except delete and open.

**Comment by ferki** [comment]
I could at least change the required allocation rules and the number of replicas of a closed index with elasticsearch-1.4.4.

**Comment by untergeek** [comment]
And when it opened, it had the correct number of replicas?  And the correct allocation?

**Comment by untergeek** [comment]
If replicas can be altered on a closed index, the solution is to alter [line 20](https://github.com/elasticsearch/curator/blob/master/curator/api/replicas.py#L20) to use `ensure_list` instead of `prune_closed`.  

And if true for allocation, the same applies to the [`prune_allocated`](https://github.com/elasticsearch/curator/blob/master/curator/api/utils.py#L275) command.

There would be no reason to add a flag for these.

However, these alterations would have to be vetted against older versions of Elasticsearch, and potentially have a client verification test done if they only work on newer versions.

**Comment by ferki** [comment]
Yes, it did not reopen the index by doing so, but reopeining it later has a result identical as if I had applied the changes while they were open. On huge datasets it really helps to be able to decrease replica count for older indices, or making sure they will be recovered to the proper hosts - so upon a later reopen, there won't be unnecessary shard juggling.

Of course all this can be achieved by normal `curl` or other API calls, but I think it would be nice to give an opt-in possibility for users who might make a good use of it (of it is to be made the default behaviour, an opt-out for those who for some reason don't want to use it). Personally I'm fine with making it default :)

And yes, it's an interesting question if/how it would work with other versions of elasticsearch. Can you do such testing easily?

**Comment by untergeek** [comment]
I would have to write tests to apply changes to closed indices, then open them again and check settings.  Our CI test sled covers versions as old as 1.0, so it'd get tested against that.

If the behavior is allowed with closed indices, I won't filter them.  I only filter closed indices to prevent errors which might result from taking action against a closed index.  A flag to turn this feature on/off would be unnecessary, in my opinion.

**Comment by ferki** [comment]
Yeah, after all it makes sense to apply changes even to closed indices if that's an allowed operation and does not have unexpected side effects (like manipulating bloom filter settings on a closed index also triggered a reopen, or adding a closed index to an alias caused querying errors).

Probably you're more familiar with the new code layout and can implement this fater than me, but let me know if you would like me to send a PR! :)

**Comment by untergeek** [comment]
The changes are only those 2 lines of code I mentioned above. But I can only accept a PR with tests, so if you're not comfortable with writing tests, I'm happy to take it up.

**Comment by ferki** [comment]
Tests are fine, and if there's still some time left to do it before the final 3.0.0 release, then I would like to take a bash at it a bit later, so I can also learn from the review ^^

**Comment by untergeek** [comment]
Be sure to add them in the test/integration folder, as those are the ones which actually test against a local Elasticsearch.
