### ISSUE TITLE
Docs on GitHub are incompatible with the current stable release

### ISSUE THREAD

**Issue by robbles** [elasticsearch/curator#288]
Is it possible that they can be kept at the API for 2.1.2 until v3 is released? This caused me some issues trying to update my curator scripts just now, and digging up the old docs is not easy.

**Comment by untergeek** [comment]
I'm so sorry for the inconvenience!  I intend to release 3.0.0 early tomorrow, barring any failures.

In the meanwhile, please make elaborate use of the `--help` flag and ask any questions here you may need to know.

**Comment by robbles** [comment]
I'll probably just upgrade to 3.0.0 right away then - the current docs make it sound a lot better :)

No worries about the mismatch, the `--help` info definitely made this problem easier to work around. One way you could avoid this in future might be to move the API docs to markdown files within the repo itself. That way it's simple to see the docs for any given release by just switching to the appropriate tag.
