### ISSUE TITLE
--dry-run doesn't show the effect of --disk-space

### ISSUE THREAD

**Issue by djs52** [elasticsearch/curator#290]
Running `curator delete --dry-run --disk-space 10 indices --all-indices` indicates that all indices are to be deleted. This is because the dry run is intercepted in the `indices` command, and the disk space check never takes place.

Instead, it should evaluate the disk space changes and list what's actually going to change.

**Comment by untergeek** [comment]
That's a valid concern.  I'll draft up a change for this.

I know this is a valid use case, but I hate it for this reason.  It forces the flow to be different.  I don't _want_ to have to pass the `dry_run` flag to the delete method for any reason, ever.  _C'est la vie._
