### ISSUE TITLE
Error if there's nothing to delete with --disk-space

### ISSUE THREAD

**Issue by djs52** [elasticsearch/curator#291]
If `--disk-space` is set high enough that there is nothing to delete, curator completes with the error:
```
2015-03-09 18:47:46,761 ERROR     Error deleting indices.  Check logs for more information.
```
This seems to be because an empty list is passed to `client.indices.delete` -- `to_csv([])` returns `None`.

Obviously this shouldn't be an error condition.

**Comment by untergeek** [comment]
I believe that #290 also addresses this by putting the disk-space filter block ahead of the final test for indices. See logger.warn('No indices matched provided args.')
